### ISSUE TITLE
Is running on Apple Silicon (M1 etc) possible?

### ISSUE THREAD

**Issue by nerixim** [vE5li/korangar#70]
I tried building and running the Rust program as per instructions but I get the following error:

```
[23:31:24] choose physical device (0ms)

thread 'main' panicked at src/main.rs:171:6:
failed to create device: a validation error occurred

Caused by:
    create_info.enabled_features: contains `wide_lines`, but this feature is not supported by the physical device
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
As I learned [here](https://community.khronos.org/t/macos-vulkan-at-runtime-vkcreatedevice-fails-when-vkphysicaldevicefeatures-widelines-vk-ture-and-doestnt-support-vkcmdsetlinewidth-api-as-well/106443/1) MacOS doesn't even support that `wide_lines` thing so is that hopeless for me?

BTW I tried ignoring by setting with `wide_lines: false` but then I get the following error:
```
[02:14:12] create resource managers -> started
  > load game archives -> started
    > loading game archive list from client/game_archives.ron
    > [error] failed to load game archive list from client/game_archives.ron; using default
    > load game data from data.grf (172ms)
    > load game data from rdata.grf (174ms)
  > load game archives -> completed (348ms)
thread 'main' panicked at src/loaders/archive/native/mod.rs:99:107:
called `Result::unwrap()` on an `Err` value: InvalidBitstream
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <korangar::loaders::archive::native::NativeArchive as korangar::loaders::archive::Archive>::get_file_by_path
   4: korangar::loaders::gamefile::GameFileLoader::get
   5: korangar::loaders::gamefile::GameFileLoader::load_patched_lua_files
   6: korangar::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
create resource managers -> failed (384ms)
```

**Comment by TheOptik** [comment]
Hey there!
`wide_lines` is indeed not supported by MacOS.

The second stacktrace you posted is not from that however. Chainging `wide_lines` to false appears to have resulted in a suitable graphics device being found.
Since we only use that feature for rendering debug information though, i think we will remove that requirement/feature so future MacOS users won't have that problem anymore.

To me it looks a lot like the provided grf files can not be read properly by korangar.
Are you running the application with unencrypted `data.grf` and `rdata.grf` files from the official kro client?

Also we've had multiple people running korangar on M1 Silicon already.
It is possible, however it seems to come with visual artifacts we have yet to debug, since @vE5li and i dont have access to a machine with an M1 Processor.

**Comment by vE5li** [comment]
Given that the only Korangar internal issue here was fixed in https://github.com/vE5li/korangar/pull/71 I will close this.
